# Generated by Django 3.2.6 on 2023-04-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
